const posts=[
{slug:'two-weeks-in-sri-lanka',category:'Sri Lanka Guide',date:'August 28, 2026',title:'Two Weeks in Sri Lanka: The Perfect Island Route',excerpt:'Ancient cities, tea-covered hills, wildlife and the southern coast in one unforgettable journey.',image:'https://images.unsplash.com/photo-1588598198321-9735fd52455b?auto=format&fit=crop&w=1000&q=85'},
{slug:'ella-train-journey',category:'Hill Country',date:'August 12, 2026',title:'Kandy to Ella: Inside Sri Lanka’s Iconic Train Journey',excerpt:'Everything to know about one of the world’s most scenic railway adventures.',image:'https://images.unsplash.com/photo-1571406761758-9a3eed5338ef?auto=format&fit=crop&w=1000&q=85'},
{slug:'sri-lanka-safari-guide',category:'Wildlife',date:'July 30, 2026',title:'A Responsible Safari Guide to Sri Lanka',excerpt:'Where to see elephants, leopards and birdlife while supporting ethical wildlife tourism.',image:'https://images.unsplash.com/photo-1581852017103-68ac65514cf7?auto=format&fit=crop&w=1000&q=85'},
{slug:'south-coast-beaches',category:'Beaches',date:'July 18, 2026',title:'Sri Lanka’s South Coast: Beyond the Famous Beaches',excerpt:'A slow journey through palm-fringed coves, surf towns and historic Galle Fort.',image:'https://images.unsplash.com/photo-1586861635167-e5223aadc9fe?auto=format&fit=crop&w=1000&q=85'},
{slug:'sigiriya-cultural-triangle',category:'Culture & Heritage',date:'June 26, 2026',title:'Sigiriya and Sri Lanka’s Cultural Triangle',excerpt:'Ancient capitals, cave temples and the extraordinary story of the Lion Rock.',image:'https://images.unsplash.com/photo-1588258524675-c6190f6b2323?auto=format&fit=crop&w=1000&q=85'},
{slug:'sri-lankan-food-guide',category:'Food',date:'June 09, 2026',title:'What to Eat in Sri Lanka: A Local Food Guide',excerpt:'From breakfast hoppers to fiery sambols, the dishes every curious traveller should try.',image:'https://images.unsplash.com/photo-1567337710282-00832b415979?auto=format&fit=crop&w=1000&q=85'}];
const card=(p,i)=>`<article class="card ${i===0?'feature':''}"><a href="post.html?slug=${encodeURIComponent(p.slug)}"><div class="media"><img loading="lazy" src="${p.image}" alt="${p.title}"></div><div class="cardbody"><div class="meta"><span>${p.category}</span><time>${p.date}</time></div><h3>${p.title}</h3><p>${p.excerpt}</p><span class="read">Read story →</span></div></a></article>`;
document.querySelector('.menu')?.addEventListener('click',()=>document.querySelector('.nav').classList.toggle('open'));
const home=document.querySelector('#home-posts');if(home)home.innerHTML=posts.slice(0,3).map(card).join('');
const grid=document.querySelector('#blog-posts');if(grid){const q=new URLSearchParams(location.search).get('q')?.toLowerCase()||'';grid.innerHTML=posts.filter(p=>(p.title+p.category+p.excerpt).toLowerCase().includes(q)).map(card).join('')||'<div class="empty-posts"><h3>No stories found</h3><p>Try another search or explore our latest Sri Lanka guides.</p></div>'}
if(document.querySelector('#post-page')){const p=posts.find(x=>x.slug===new URLSearchParams(location.search).get('slug'))||posts[0];document.title=p.title+' | Travel Vacation Adventure';document.querySelector('#post-title').textContent=p.title;document.querySelector('#post-cat').textContent=p.category;document.querySelector('#post-date').textContent=p.date;document.querySelector('#post-image').src=p.image;document.querySelector('#post-image').alt=p.title;document.querySelector('#post-lead').textContent=p.excerpt;document.querySelector('meta[name=description]').content=p.excerpt}
